### ISSUE TITLE
Gradio Doesn't Open in Web Browser

### ISSUE THREAD

**Issue by MachineSaver** [knowsuchagency/pdf-to-podcast#3]
![image](https://github.com/user-attachments/assets/c35e12ce-2682-4c5b-81fe-dee702b78a4d)

I followed the instructions for setup and had no issues until trying to run the main function of the app.

> machine_saver@LAPTOP-QU5MQ357 MINGW64 ~/Documents
> $ git clone https://github.com/knowsuchagency/pdf-to-podcast.git
> Cloning into 'pdf-to-podcast'...
> remote: Enumerating objects: 135, done.
> remote: Counting objects: 100% (71/71), done.
> remote: Compressing objects: 100% (22/22), done.
> remote: Total 135 (delta 50), reused 49 (delta 49), pack-reused 64 (from 1)
> Receiving objects: 100% (135/135), 4.26 MiB | 9.84 MiB/s, done.
> Resolving deltas: 100% (74/74), done.
> 
> machine_saver@LAPTOP-QU5MQ357 MINGW64 ~/Documents
> $ cd pdf-to-podcast
> 
> machine_saver@LAPTOP-QU5MQ357 MINGW64 ~/Documents/pdf-to-podcast (main)
> $ ls -a
> ./  ../  .dockerignore  .git/  .gitignore  Dockerfile  LICENSE  README.md  description.md  docker-compose.yml  examples/  head.html  main.py  requirements.txt  static/
> 
> machine_saver@LAPTOP-QU5MQ357 MINGW64 ~/Documents/pdf-to-podcast (main)
> $ python -m venv .venv
> 
> machine_saver@LAPTOP-QU5MQ357 MINGW64 ~/Documents/pdf-to-podcast (main)
> $ source .venv/bin/activate
> bash: .venv/bin/activate: No such file or directory
> 
> machine_saver@LAPTOP-QU5MQ357 MINGW64 ~/Documents/pdf-to-podcast (main)
> $ source .venv/Scripts/activate
> (.venv)
> machine_saver@LAPTOP-QU5MQ357 MINGW64 ~/Documents/pdf-to-podcast (main)
> $ pip install -r requirements.txt
> Collecting gradio~=4.36 (from -r requirements.txt (line 1))
>   Downloading gradio-4.44.1-py3-none-any.whl (18.1 MB)
>      --------------------------------------- 18.1/18.1 MB 31.1 MB/s eta 0:00:00
> Collecting promptic==0.7.5 (from -r requirements.txt (line 2))
>   Using cached promptic-0.7.5-py2.py3-none-any.whl (7.7 kB)
> Collecting pydantic~=2.7 (from -r requirements.txt (line 3))
>   Downloading pydantic-2.9.2-py3-none-any.whl (434 kB)
>      ------------------------------------- 434.9/434.9 kB 26.5 MB/s eta 0:00:00
> Collecting google-generativeai~=0.6 (from -r requirements.txt (line 4))
>   Downloading google_generativeai-0.8.3-py3-none-any.whl (160 kB)
>      -------------------------------------- 160.8/160.8 kB 9.4 MB/s eta 0:00:00
> Collecting loguru~=0.7 (from -r requirements.txt (line 5))
>   Downloading loguru-0.7.2-py3-none-any.whl (62 kB)
>      ---------------------------------------- 62.5/62.5 kB ? eta 0:00:00
> Collecting pypdf~=4.1 (from -r requirements.txt (line 6))
>   Downloading pypdf-4.3.1-py3-none-any.whl (295 kB)
>      ---------------------------------------- 295.8/295.8 kB ? eta 0:00:00
> Collecting tenacity~=8.3 (from -r requirements.txt (line 7))
>   Downloading tenacity-8.5.0-py3-none-any.whl (28 kB)
> Collecting sentry-sdk~=2.5 (from -r requirements.txt (line 8))
>   Downloading sentry_sdk-2.16.0-py2.py3-none-any.whl (313 kB)
>      ------------------------------------- 313.8/313.8 kB 19.0 MB/s eta 0:00:00
> Collecting granian~=1.4 (from -r requirements.txt (line 9))
>   Downloading granian-1.6.0-cp311-none-win_amd64.whl (2.0 MB)
>      ---------------------------------------- 2.0/2.0 MB 31.3 MB/s eta 0:00:00
> Collecting litellm~=1.38 (from promptic==0.7.5->-r requirements.txt (line 2))
>   Downloading litellm-1.48.19-py3-none-any.whl (6.3 MB)
>      ---------------------------------------- 6.3/6.3 MB 36.4 MB/s eta 0:00:00
> Collecting aiofiles<24.0,>=22.0 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached aiofiles-23.2.1-py3-none-any.whl (15 kB)
> Collecting anyio<5.0,>=3.0 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached anyio-4.6.0-py3-none-any.whl (89 kB)
> Collecting fastapi<1.0 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached fastapi-0.115.0-py3-none-any.whl (94 kB)
> Collecting ffmpy (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached ffmpy-0.4.0-py3-none-any.whl (5.8 kB)
> Collecting gradio-client==1.3.0 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached gradio_client-1.3.0-py3-none-any.whl (318 kB)
> Collecting httpx>=0.24.1 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached httpx-0.27.2-py3-none-any.whl (76 kB)
> Collecting huggingface-hub>=0.19.3 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached huggingface_hub-0.25.1-py3-none-any.whl (436 kB)
> Collecting importlib-resources<7.0,>=1.3 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached importlib_resources-6.4.5-py3-none-any.whl (36 kB)
> Collecting jinja2<4.0 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached jinja2-3.1.4-py3-none-any.whl (133 kB)
> Collecting markupsafe~=2.0 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached MarkupSafe-2.1.5-cp311-cp311-win_amd64.whl (17 kB)
> Collecting matplotlib~=3.0 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached matplotlib-3.9.2-cp311-cp311-win_amd64.whl (7.8 MB)
> Collecting numpy<3.0,>=1.0 (from gradio~=4.36->-r requirements.txt (line 1))
>   Downloading numpy-2.1.2-cp311-cp311-win_amd64.whl (12.9 MB)
>      --------------------------------------- 12.9/12.9 MB 38.5 MB/s eta 0:00:00
> Collecting orjson~=3.0 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached orjson-3.10.7-cp311-none-win_amd64.whl (137 kB)
> Collecting packaging (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached packaging-24.1-py3-none-any.whl (53 kB)
> Collecting pandas<3.0,>=1.0 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached pandas-2.2.3-cp311-cp311-win_amd64.whl (11.6 MB)
> Collecting pillow<11.0,>=8.0 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached pillow-10.4.0-cp311-cp311-win_amd64.whl (2.6 MB)
> Collecting pydub (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached pydub-0.25.1-py2.py3-none-any.whl (32 kB)
> Collecting python-multipart>=0.0.9 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached python_multipart-0.0.12-py3-none-any.whl (23 kB)
> Collecting pyyaml<7.0,>=5.0 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached PyYAML-6.0.2-cp311-cp311-win_amd64.whl (161 kB)
> Collecting ruff>=0.2.2 (from gradio~=4.36->-r requirements.txt (line 1))
>   Downloading ruff-0.6.9-py3-none-win_amd64.whl (9.4 MB)
>      ---------------------------------------- 9.4/9.4 MB 37.4 MB/s eta 0:00:00
> Collecting semantic-version~=2.0 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
> Collecting tomlkit==0.12.0 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached tomlkit-0.12.0-py3-none-any.whl (37 kB)
> Collecting typer<1.0,>=0.12 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached typer-0.12.5-py3-none-any.whl (47 kB)
> Collecting typing-extensions~=4.0 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached typing_extensions-4.12.2-py3-none-any.whl (37 kB)
> Collecting urllib3~=2.0 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached urllib3-2.2.3-py3-none-any.whl (126 kB)
> Collecting uvicorn>=0.14.0 (from gradio~=4.36->-r requirements.txt (line 1))
>   Using cached uvicorn-0.31.0-py3-none-any.whl (63 kB)
> Collecting fsspec (from gradio-client==1.3.0->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached fsspec-2024.9.0-py3-none-any.whl (179 kB)
> Collecting websockets<13.0,>=10.0 (from gradio-client==1.3.0->gradio~=4.36->-r requirements.txt (line 1))
>   Downloading websockets-12.0-cp311-cp311-win_amd64.whl (124 kB)
>      -------------------------------------- 125.0/125.0 kB 7.2 MB/s eta 0:00:00
> Collecting annotated-types>=0.6.0 (from pydantic~=2.7->-r requirements.txt (line 3))
>   Using cached annotated_types-0.7.0-py3-none-any.whl (13 kB)
> Collecting pydantic-core==2.23.4 (from pydantic~=2.7->-r requirements.txt (line 3))
>   Downloading pydantic_core-2.23.4-cp311-none-win_amd64.whl (1.9 MB)
>      ---------------------------------------- 1.9/1.9 MB 40.6 MB/s eta 0:00:00
> Collecting google-ai-generativelanguage==0.6.10 (from google-generativeai~=0.6->-r requirements.txt (line 4))
>   Downloading google_ai_generativelanguage-0.6.10-py3-none-any.whl (760 kB)
>      ------------------------------------- 760.0/760.0 kB 23.4 MB/s eta 0:00:00
> Collecting google-api-core (from google-generativeai~=0.6->-r requirements.txt (line 4))
>   Downloading google_api_core-2.20.0-py3-none-any.whl (142 kB)
>      -------------------------------------- 142.2/142.2 kB 8.8 MB/s eta 0:00:00
> Collecting google-api-python-client (from google-generativeai~=0.6->-r requirements.txt (line 4))
>   Downloading google_api_python_client-2.148.0-py2.py3-none-any.whl (12.3 MB)
>      --------------------------------------- 12.3/12.3 MB 36.3 MB/s eta 0:00:00
> Collecting google-auth>=2.15.0 (from google-generativeai~=0.6->-r requirements.txt (line 4))
>   Downloading google_auth-2.35.0-py2.py3-none-any.whl (208 kB)
>      ------------------------------------- 209.0/209.0 kB 13.2 MB/s eta 0:00:00
> Collecting protobuf (from google-generativeai~=0.6->-r requirements.txt (line 4))
>   Downloading protobuf-5.28.2-cp310-abi3-win_amd64.whl (431 kB)
>      ------------------------------------- 431.5/431.5 kB 26.3 MB/s eta 0:00:00
> Collecting tqdm (from google-generativeai~=0.6->-r requirements.txt (line 4))
>   Using cached tqdm-4.66.5-py3-none-any.whl (78 kB)
> Collecting proto-plus<2.0.0dev,>=1.22.3 (from google-ai-generativelanguage==0.6.10->google-generativeai~=0.6->-r requirements.txt (line 4))
>   Downloading proto_plus-1.24.0-py3-none-any.whl (50 kB)
>      ---------------------------------------- 50.1/50.1 kB 2.5 MB/s eta 0:00:00
> Collecting colorama>=0.3.4 (from loguru~=0.7->-r requirements.txt (line 5))
>   Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
> Collecting win32-setctime>=1.0.0 (from loguru~=0.7->-r requirements.txt (line 5))
>   Downloading win32_setctime-1.1.0-py3-none-any.whl (3.6 kB)
> Collecting certifi (from sentry-sdk~=2.5->-r requirements.txt (line 8))
>   Using cached certifi-2024.8.30-py3-none-any.whl (167 kB)
> Collecting click>=8.0.0 (from granian~=1.4->-r requirements.txt (line 9))
>   Using cached click-8.1.7-py3-none-any.whl (97 kB)
> Collecting idna>=2.8 (from anyio<5.0,>=3.0->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached idna-3.10-py3-none-any.whl (70 kB)
> Collecting sniffio>=1.1 (from anyio<5.0,>=3.0->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached sniffio-1.3.1-py3-none-any.whl (10 kB)
> Collecting starlette<0.39.0,>=0.37.2 (from fastapi<1.0->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached starlette-0.38.6-py3-none-any.whl (71 kB)
> Collecting cachetools<6.0,>=2.0.0 (from google-auth>=2.15.0->google-generativeai~=0.6->-r requirements.txt (line 4))
>   Downloading cachetools-5.5.0-py3-none-any.whl (9.5 kB)
> Collecting pyasn1-modules>=0.2.1 (from google-auth>=2.15.0->google-generativeai~=0.6->-r requirements.txt (line 4))
>   Downloading pyasn1_modules-0.4.1-py3-none-any.whl (181 kB)
>      ---------------------------------------- 181.5/181.5 kB ? eta 0:00:00
> Collecting rsa<5,>=3.1.4 (from google-auth>=2.15.0->google-generativeai~=0.6->-r requirements.txt (line 4))
>   Downloading rsa-4.9-py3-none-any.whl (34 kB)
> Collecting httpcore==1.* (from httpx>=0.24.1->gradio~=4.36->-r requirements.txt (line 1))
>   Downloading httpcore-1.0.6-py3-none-any.whl (78 kB)
>      ---------------------------------------- 78.0/78.0 kB ? eta 0:00:00
> Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx>=0.24.1->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached h11-0.14.0-py3-none-any.whl (58 kB)
> Collecting filelock (from huggingface-hub>=0.19.3->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached filelock-3.16.1-py3-none-any.whl (16 kB)
> Collecting requests (from huggingface-hub>=0.19.3->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached requests-2.32.3-py3-none-any.whl (64 kB)
> Collecting aiohttp (from litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Downloading aiohttp-3.10.9-cp311-cp311-win_amd64.whl (381 kB)
>      ------------------------------------- 382.0/382.0 kB 23.2 MB/s eta 0:00:00
> Collecting importlib-metadata>=6.8.0 (from litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Using cached importlib_metadata-8.5.0-py3-none-any.whl (26 kB)
> Collecting jsonschema<5.0.0,>=4.22.0 (from litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Using cached jsonschema-4.23.0-py3-none-any.whl (88 kB)
> Collecting openai>=1.51.0 (from litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Downloading openai-1.51.2-py3-none-any.whl (383 kB)
>      ------------------------------------- 383.7/383.7 kB 12.0 MB/s eta 0:00:00
> Collecting python-dotenv>=0.2.0 (from litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Using cached python_dotenv-1.0.1-py3-none-any.whl (19 kB)
> Collecting tiktoken>=0.7.0 (from litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Downloading tiktoken-0.8.0-cp311-cp311-win_amd64.whl (884 kB)
>      ------------------------------------- 884.5/884.5 kB 58.3 MB/s eta 0:00:00
> Collecting tokenizers (from litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Using cached tokenizers-0.20.0-cp311-none-win_amd64.whl (2.3 MB)
> Collecting contourpy>=1.0.1 (from matplotlib~=3.0->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached contourpy-1.3.0-cp311-cp311-win_amd64.whl (217 kB)
> Collecting cycler>=0.10 (from matplotlib~=3.0->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached cycler-0.12.1-py3-none-any.whl (8.3 kB)
> Collecting fonttools>=4.22.0 (from matplotlib~=3.0->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached fonttools-4.54.1-cp311-cp311-win_amd64.whl (2.2 MB)
> Collecting kiwisolver>=1.3.1 (from matplotlib~=3.0->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached kiwisolver-1.4.7-cp311-cp311-win_amd64.whl (56 kB)
> Collecting pyparsing>=2.3.1 (from matplotlib~=3.0->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached pyparsing-3.1.4-py3-none-any.whl (104 kB)
> Collecting python-dateutil>=2.7 (from matplotlib~=3.0->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
> Collecting pytz>=2020.1 (from pandas<3.0,>=1.0->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached pytz-2024.2-py2.py3-none-any.whl (508 kB)
> Collecting tzdata>=2022.7 (from pandas<3.0,>=1.0->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached tzdata-2024.2-py2.py3-none-any.whl (346 kB)
> Collecting shellingham>=1.3.0 (from typer<1.0,>=0.12->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached shellingham-1.5.4-py2.py3-none-any.whl (9.8 kB)
> Collecting rich>=10.11.0 (from typer<1.0,>=0.12->gradio~=4.36->-r requirements.txt (line 1))
>   Downloading rich-13.9.2-py3-none-any.whl (242 kB)
>      ------------------------------------- 242.1/242.1 kB 15.5 MB/s eta 0:00:00
> Collecting googleapis-common-protos<2.0.dev0,>=1.56.2 (from google-api-core->google-generativeai~=0.6->-r requirements.txt (line 4))
>   Downloading googleapis_common_protos-1.65.0-py2.py3-none-any.whl (220 kB)
>      ---------------------------------------- 220.9/220.9 kB ? eta 0:00:00
> Collecting httplib2<1.dev0,>=0.19.0 (from google-api-python-client->google-generativeai~=0.6->-r requirements.txt (line 4))
>   Downloading httplib2-0.22.0-py3-none-any.whl (96 kB)
>      ---------------------------------------- 96.9/96.9 kB ? eta 0:00:00
> Collecting google-auth-httplib2<1.0.0,>=0.2.0 (from google-api-python-client->google-generativeai~=0.6->-r requirements.txt (line 4))
>   Downloading google_auth_httplib2-0.2.0-py2.py3-none-any.whl (9.3 kB)
> Collecting uritemplate<5,>=3.0.1 (from google-api-python-client->google-generativeai~=0.6->-r requirements.txt (line 4))
>   Downloading uritemplate-4.1.1-py2.py3-none-any.whl (10 kB)
> Collecting grpcio<2.0dev,>=1.33.2 (from google-api-core->google-generativeai~=0.6->-r requirements.txt (line 4))
>   Downloading grpcio-1.66.2-cp311-cp311-win_amd64.whl (4.3 MB)
>      ---------------------------------------- 4.3/4.3 MB 46.0 MB/s eta 0:00:00
> Collecting grpcio-status<2.0.dev0,>=1.33.2 (from google-api-core->google-generativeai~=0.6->-r requirements.txt (line 4))
>   Downloading grpcio_status-1.66.2-py3-none-any.whl (14 kB)
> Collecting zipp>=3.20 (from importlib-metadata>=6.8.0->litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Downloading zipp-3.20.2-py3-none-any.whl (9.2 kB)
> Collecting attrs>=22.2.0 (from jsonschema<5.0.0,>=4.22.0->litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Using cached attrs-24.2.0-py3-none-any.whl (63 kB)
> Collecting jsonschema-specifications>=2023.03.6 (from jsonschema<5.0.0,>=4.22.0->litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Downloading jsonschema_specifications-2024.10.1-py3-none-any.whl (18 kB)
> Collecting referencing>=0.28.4 (from jsonschema<5.0.0,>=4.22.0->litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Using cached referencing-0.35.1-py3-none-any.whl (26 kB)
> Collecting rpds-py>=0.7.1 (from jsonschema<5.0.0,>=4.22.0->litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Using cached rpds_py-0.20.0-cp311-none-win_amd64.whl (213 kB)
> Collecting distro<2,>=1.7.0 (from openai>=1.51.0->litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Using cached distro-1.9.0-py3-none-any.whl (20 kB)
> Collecting jiter<1,>=0.4.0 (from openai>=1.51.0->litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Downloading jiter-0.6.1-cp311-none-win_amd64.whl (201 kB)
>      ---------------------------------------- 202.0/202.0 kB ? eta 0:00:00
> Collecting pyasn1<0.7.0,>=0.4.6 (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai~=0.6->-r requirements.txt (line 4))
>   Downloading pyasn1-0.6.1-py3-none-any.whl (83 kB)
>      ---------------------------------------- 83.1/83.1 kB ? eta 0:00:00
> Collecting six>=1.5 (from python-dateutil>=2.7->matplotlib~=3.0->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
> Collecting charset-normalizer<4,>=2 (from requests->huggingface-hub>=0.19.3->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached charset_normalizer-3.3.2-cp311-cp311-win_amd64.whl (99 kB)
> Collecting markdown-it-py>=2.2.0 (from rich>=10.11.0->typer<1.0,>=0.12->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
> Collecting pygments<3.0.0,>=2.13.0 (from rich>=10.11.0->typer<1.0,>=0.12->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached pygments-2.18.0-py3-none-any.whl (1.2 MB)
> Collecting regex>=2022.1.18 (from tiktoken>=0.7.0->litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Using cached regex-2024.9.11-cp311-cp311-win_amd64.whl (274 kB)
> Collecting aiohappyeyeballs>=2.3.0 (from aiohttp->litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Downloading aiohappyeyeballs-2.4.3-py3-none-any.whl (14 kB)
> Collecting aiosignal>=1.1.2 (from aiohttp->litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
> Collecting frozenlist>=1.1.1 (from aiohttp->litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Using cached frozenlist-1.4.1-cp311-cp311-win_amd64.whl (50 kB)
> Collecting multidict<7.0,>=4.5 (from aiohttp->litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Using cached multidict-6.1.0-cp311-cp311-win_amd64.whl (28 kB)
> Collecting yarl<2.0,>=1.12.0 (from aiohttp->litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Downloading yarl-1.14.0-cp311-cp311-win_amd64.whl (83 kB)
>      ---------------------------------------- 83.8/83.8 kB 4.6 MB/s eta 0:00:00
> Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.11.0->typer<1.0,>=0.12->gradio~=4.36->-r requirements.txt (line 1))
>   Using cached mdurl-0.1.2-py3-none-any.whl (10.0 kB)
> Collecting propcache>=0.2.0 (from yarl<2.0,>=1.12.0->aiohttp->litellm~=1.38->promptic==0.7.5->-r requirements.txt (line 2))
>   Downloading propcache-0.2.0-cp311-cp311-win_amd64.whl (44 kB)
>      -------------------------------------- 44.9/44.9 kB 737.9 kB/s eta 0:00:00
> Installing collected packages: pytz, pydub, zipp, win32-setctime, websockets, urllib3, uritemplate, tzdata, typing-extensions, tomlkit, tenacity, sniffio, six, shellingham, semantic-version, ruff, rpds-py, regex, pyyaml, python-multipart, python-dotenv, pypdf, pyparsing, pygments, pyasn1, protobuf, propcache, pillow, packaging, orjson, numpy, multidict, mdurl, markupsafe, kiwisolver, jiter, importlib-resources, idna, h11, grpcio, fsspec, frozenlist, fonttools, filelock, ffmpy, distro, cycler, colorama, charset-normalizer, certifi, cachetools, attrs, annotated-types, aiohappyeyeballs, aiofiles, yarl, tqdm, sentry-sdk, rsa, requests, referencing, python-dateutil, pydantic-core, pyasn1-modules, proto-plus, markdown-it-py, loguru, jinja2, importlib-metadata, httplib2, httpcore, googleapis-common-protos, contourpy, click, anyio, aiosignal, uvicorn, tiktoken, starlette, rich, pydantic, pandas, matplotlib, jsonschema-specifications, huggingface-hub, httpx, grpcio-status, granian, google-auth, aiohttp, typer, tokenizers, openai, jsonschema, gradio-client, google-auth-httplib2, google-api-core, fastapi, litellm, gradio, google-api-python-client, promptic, google-ai-generativelanguage, google-generativeai
> Successfully installed aiofiles-23.2.1 aiohappyeyeballs-2.4.3 aiohttp-3.10.9 aiosignal-1.3.1 annotated-types-0.7.0 anyio-4.6.0 attrs-24.2.0 cachetools-5.5.0 certifi-2024.8.30 charset-normalizer-3.3.2 click-8.1.7 colorama-0.4.6 contourpy-1.3.0 cycler-0.12.1 distro-1.9.0 fastapi-0.115.0 ffmpy-0.4.0 filelock-3.16.1 fonttools-4.54.1 frozenlist-1.4.1 fsspec-2024.9.0 google-ai-generativelanguage-0.6.10 google-api-core-2.20.0 google-api-python-client-2.148.0 google-auth-2.35.0 google-auth-httplib2-0.2.0 google-generativeai-0.8.3 googleapis-common-protos-1.65.0 gradio-4.44.1 gradio-client-1.3.0 granian-1.6.0 grpcio-1.66.2 grpcio-status-1.66.2 h11-0.14.0 httpcore-1.0.6 httplib2-0.22.0 httpx-0.27.2 huggingface-hub-0.25.1 idna-3.10 importlib-metadata-8.5.0 importlib-resources-6.4.5 jinja2-3.1.4 jiter-0.6.1 jsonschema-4.23.0 jsonschema-specifications-2024.10.1 kiwisolver-1.4.7 litellm-1.48.19 loguru-0.7.2 markdown-it-py-3.0.0 markupsafe-2.1.5 matplotlib-3.9.2 mdurl-0.1.2 multidict-6.1.0 numpy-2.1.2 openai-1.51.2 orjson-3.10.7 packaging-24.1 pandas-2.2.3 pillow-10.4.0 promptic-0.7.5 propcache-0.2.0 proto-plus-1.24.0 protobuf-5.28.2 pyasn1-0.6.1 pyasn1-modules-0.4.1 pydantic-2.9.2 pydantic-core-2.23.4 pydub-0.25.1 pygments-2.18.0 pyparsing-3.1.4 pypdf-4.3.1 python-dateutil-2.9.0.post0 python-dotenv-1.0.1 python-multipart-0.0.12 pytz-2024.2 pyyaml-6.0.2 referencing-0.35.1 regex-2024.9.11 requests-2.32.3 rich-13.9.2 rpds-py-0.20.0 rsa-4.9 ruff-0.6.9 semantic-version-2.10.0 sentry-sdk-2.16.0 shellingham-1.5.4 six-1.16.0 sniffio-1.3.1 starlette-0.38.6 tenacity-8.5.0 tiktoken-0.8.0 tokenizers-0.20.0 tomlkit-0.12.0 tqdm-4.66.5 typer-0.12.5 typing-extensions-4.12.2 tzdata-2024.2 uritemplate-4.1.1 urllib3-2.2.3 uvicorn-0.31.0 websockets-12.0 win32-setctime-1.1.0 yarl-1.14.0 zipp-3.20.2
> 
> [notice] A new release of pip is available: 23.1.2 -> 24.2
> [notice] To update, run: python.exe -m pip install --upgrade pip
> (.venv)
> machine_saver@LAPTOP-QU5MQ357 MINGW64 ~/Documents/pdf-to-podcast (main)
> $ export GEMINI_API_KEY="REDACTED"
> (.venv)
> machine_saver@LAPTOP-QU5MQ357 MINGW64 ~/Documents/pdf-to-podcast (main)
> $ export OPENAI_API_KEY="REDACTED"
> (.venv)
> machine_saver@LAPTOP-QU5MQ357 MINGW64 ~/Documents/pdf-to-podcast (main)
> $ python main.py
> C:\Users\machine_saver\Documents\pdf-to-podcast\.venv\Lib\site-packages\gradio\helpers.py:370: UserWarning: Examples will be cached but not all input components have example values. This may result in an exception being thrown by your function. If you do get an error while caching examples, make sure all of your inputs have example values for all of your examples or you provide default values for those particular parameters in your function.
>   warnings.warn(

**Comment by knowsuchagency** [comment]
this should be resolved
