### ISSUE TITLE
Ollama API integration 

### ISSUE THREAD

**Issue by pachieh** [knowsuchagency/pdf-to-podcast#4]
I am trying to figure out how to integrate Ollama for full local integration. Running into an issue of using the API streaming endpoint vs the API key that you require. 

Any idea on how to fix or are there plans to integrate Ollama?

**Comment by knowsuchagency** [comment]
This project uses https://github.com/knowsuchagency/promptic which sits on top of litellm and should support ollama https://docs.litellm.ai/docs/providers/ollama
