### ISSUE TITLE
Instructions incomplete?

### ISSUE THREAD

**Issue by pbriesch** [knowsuchagency/pdf-to-podcast#5]
When I  follow the instruction for installation I get stuck at

`uv sync
uv: command not found`

Could you please update the instructions?

Thank you!

**Comment by OlivierZanders** [comment]
I had the same problem! The easy fix is doing:

`pip install uv`

If this does not fix your problem, please check this: https://stackoverflow.com/questions/78153381/using-uv-to-install-packages-in-the-bitnami-deepspeed0-14-0-docker-image-fails

**Comment by knowsuchagency** [comment]
Thanks @OlivierZanders that's correct!
